version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass1234KC
      POSTGRES_USER: admin
      POSTGRES_DB: empresa
    volumes:
      - /var/lib/postgresql/data
  
  adminpg:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: examen@uisrael.edu.ec
      PGADMIN_DEFAULT_PASSWORD: exates123
      PGADMIN_LISTEN_PORT: 80
    depends_on:
      - db

volumes:
  db_data: 
  adminpg_data:   